---
- hosts: aws_ec2
  become: true
  become_user: root
  gather_facts: false
  vars:
     image_name: doppal/myprivate-repo:$BUILD_NUMBER
     docker_password: "${DOCKER_PASSWORD}"
  tasks:
  - name: print
    debug:
     msg: "These servers were built using the password of '{{ docker_password }}'. Please retain this for later use."
  - name: Install docker
    shell: "sudo amazon-linux-extras install docker -y"
  - name: start docker
    service: name=docker state=started
  - name: Install docker python module
    pip:
      name:
      - docker
      - docker-compose
  - name: Install docker-compose
    get_url:
        url: https://github.com/docker/compose/releases/download/1.21.0/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: +x
  - name: Add ec2-user to docker group
    user:
      name: ec2-user
      groups: docker
      append: yes
  - name: Reconnect to server session
    meta: reset_connection
  - name: docker login
    docker_login:
       registry_url: https://index.docker.io/v1/
       username: doppal
       password: "{{docker_password}}"
  - name: Run the docker image
    docker_container: 
       name: addbookcontainer 
       image: "{{image_name}}"